name: Publish Docker Image
on:
  workflow_dispatch:
    inputs:
      publishStable:
        type: boolean
        description: publish stable
        default: false
      targetRegistry:
        type: choice
        description: Target Registry
        default: Docker Hub
        options:
          - Docker Hub

jobs:
  UnitTest:
    name: Run Go unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.20.2

      - run: go version

      - name: run GO test
        run: |
          echo "Testing go functions"
  
  Publish:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    needs: [UnitTest]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.20.2

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: create build version
        id: get_version
        run: |
          version=$(go run main.go -v)

          if [ "${{ github.event.inputs.publishStable }}" == false ]
          then
            echo "tag=$version.${{ github.run_number}}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=$version" >> "$GITHUB_OUTPUT"
          fi

      - name: login to Docker Hub
        if: github.event.inputs.targetRegistry == 'Docker Hub'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: hidetran/kuberity:v${{ steps.get_version.outputs.tag }}